# Generated by Django 5.1.6 on 2025-03-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('train_number', models.IntegerField()),
                ('baggage_law', models.IntegerField()),
            ],
        ),
    ]
